version: '3'
services:
  annotate_mysql:
    container_name: annotate_mysql
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASS=root
      - MYSQL_USER=root
    volumes:
      - datavolume:/var/lib/docker_mysql
    ports:
      - "6603:3306"
  annotate:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    environment:
      - DB_HOST=annotate_mysql
      - DB_PORT=6603
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
volumes:
  datavolume:
