version: '3'
services:
  annotate:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
