version: '3'
services:
  annotate:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=6603
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
  mysql:
    container_name: mysql
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASS=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
    volumes:
      - datavolume:/var/lib/docker_mysql
    ports:
      - "6603:3306"
volumes:
  datavolume:
