version: '3.8'
services:
  annotate_mariadb:
    container_name: annotate_mariadb
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASS=root
      - MYSQL_USER=root
    volumes:
      - datavolume:/var/lib/docker_mysql
    networks:
      - annotate_network
  annotate:
    restart: unless-stopped
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    environment:
      - DB_HOST=annotate_mariadb
      - DB_PORT=3306
      - DB_PASSWORD=root
      - DB_USER=root
    networks:
      - annotate_network
    tmpfs:
      - /tmp:rw
volumes:
  datavolume:
networks:
  annotate_network:
    driver: bridge
