#!/bin/bash

file=$1
# Temporäres Verzeichnis unter /tmp, pro Apache-User
venv_dir="/tmp/get_hash_venv"

# Erstelle venv, falls sie nicht existiert
if [[ ! -d "$venv_dir" ]]; then
    python3 -m venv "$venv_dir" || { echo "Failed to create venv"; exit 1; }
    "$venv_dir/bin/pip" install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; }
    "$venv_dir/bin/pip" install pillow imagehash || { echo "Failed to install packages"; exit 1; }
fi

# Python-Befehl innerhalb der venv ausführen
function run_python_command {
    "$venv_dir/bin/python" - <<END
import sys
from PIL import Image
import imagehash

file_path = "$file"
hash_val = str(imagehash.phash(Image.open(file_path).resize((512, 512))))
print(hash_val)
END

    return $?
}

run_python_command
exit_code=$?

if [[ $exit_code -gt 0 ]]; then
    echo "Python failed with exit_code $exit_code"
    exit 1
fi
