#!/bin/bash

set -e

php test_batch_upload.php

source tests/php_syntax_check

source tests/bash_syntax_check

source tests/run_in_docker

source tests/empty_page

source tests/linkchecker

source tests/playwright
