#!/bin/bash

source tests/php_syntax_check

source tests/bash_syntax_check

source tests/run_in_docker

bash tests/empty_page
exit_code=$?
if [[ $exit_code -ne 0 ]]; then
	echo "bash tests/empty_page failed with exit_code $exit_code"
	exit 1
fi


bash tests/upload_model
exit_code=$?
if [[ $exit_code -ne 0 ]]; then
	echo "bash tests/upload_model failed with exit_code $exit_code"
	exit 1
fi

source tests/venv

source tests/linkchecker

source tests/playwright
