#!/bin/bash

source tests/php_syntax_check

source tests/bash_syntax_check

source tests/run_in_docker

source tests/empty_page

source tests/upload_model

source tests/venv

source tests/linkchecker

source tests/playwright
