#!/bin/bash

#wget http://localhost:9912/export_annotations.php?model=yolo11n.yaml&max_files=0&epochs=2000&validation_split=0&test_split=0&empty=0&group_by_perception_hash=0&only_curated=0&only_uncurated=0&max_truncation=100
