#!/bin/bash

if ! command -v curl 2>&1 >/dev/null; then
	echo "curl not installed. Try sudo apt install -y curl"
	exit 255
fi

source tests/venv

curl localhost:9912 2>/dev/null >/dev/null || bash tests/run_in_docker

[ -f "$HOME/.playwright_deps_installed" ] || {
	echo "====== pip3 install playwright ======" && {
		pip3 install playwright || {
			echo "pip3 install playwright failed. Are you online?" 
			rm -rf ~/.annotate_test_env
			exit 1
		}
	} &&
	echo "====== playwright install chromium ======" && \
	playwright install chromium && \
	{
		which chromium 2> /dev/null >/dev/null || sudo apt install chromium
	} && \
	echo "====== python3 -m playwright install --with-deps chromium ======" && \
	python3 -m playwright install --with-deps chromium && \
	touch "$HOME/.playwright_deps_installed";
}

export DELETE_KEY=$(uuidgen); \
	CID=$(docker ps --format '{{.ID}} {{.Names}}' | grep annotate_test_annotate | awk '{print $1}'); \
	docker exec "$CID" sh -c "echo '$DELETE_KEY' > /etc/delete_all_key"; \
	echo "KEY: $DELETE_KEY"

echo "Deleting all currently existing data..."
curl "http://localhost:9912/delete_all_data.php?delete_key=$DELETE_KEY"

echo "Testing if 0 images are annotated"

NR_ANNOTATED_ZERO_LINES=$(curl -sS localhost:9912/print_home.php | grep "Annotated: 0" | wc -l)
if [[ $NR_ANNOTATED_ZERO_LINES -ne 1 ]]; then
	echo "There was an error getting print_home.php: searching for 'Annotated: 0' yielded $NR_ANNOTATED_ZERO_LINES results instead of 1"
	exit 1
fi

python3 _run_tests.py $*
exit_code=$?
