#!/bin/bash

if ! command -v curl 2>&1 >/dev/null; then
	echo "curl not installed. Try sudo apt install -y curl"
	exit 255
fi

source tests/venv

curl localhost:9912 2>/dev/null >/dev/null || bash tests/run_in_docker

[ -f "$HOME/.playwright_deps_installed" ] || {
	echo "====== pip3 install playwright ======" && {
		pip3 install playwright || {
			echo "pip3 install playwright failed. Are you online?" 
			rm -rf ~/.annotate_test_env
			exit 1
		}
	} &&
	echo "====== playwright install chromium ======" && \
	playwright install chromium && \
	{
		which chromium 2> /dev/null >/dev/null || sudo apt install chromium
	} && \
	echo "====== python3 -m playwright install --with-deps chromium ======" && \
	python3 -m playwright install --with-deps chromium && \
	touch "$HOME/.playwright_deps_installed";
}

python3 _run_tests.py $*
exit_code=$?
