#!/bin/bash

if ! command -v curl 2>&1 >/dev/null; then
	echo "curl not installed. Try sudo apt install -y curl"
	exit 255
fi

source tests/venv

curl localhost:9912 2>/dev/null >/dev/null || bash tests/run_in_docker

echo "====== pip3 install playwright ======"
if ! pip3 install playwright; then
	echo "pip3 install playwright failed. Are you online?"
	rm -rf ~/.annotate_test_env
	exit 1
fi

echo "====== playwright install chromium ======"
playwright install chromium

echo "====== python3 -m playwright install --with-deps chromium ======"

if ! which chromium 2> /dev/null >/dev/null; then
	sudo apt install chromium
fi

python3 -m playwright install --with-deps chromium

echo "====== Run tests ======"
python3 _run_tests.py $*
exit_code=$?
echo "====== Ran tests ======"
